[package]
name = "yuki"
version = "0.1.0"
authors = ["Dean Calver <me@deanoc.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
cuda-config = "0.1.0"
bindgen = "0.53.1"
